"""Focused verifier tests for MUST-to-test traceability (v0.3)."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
VERIFIER = ROOT / "scripts" / "verify_traceability.py"
INVENTORY = ROOT / "docs" / "TRACEABILITY_V0_2.json"
REPORT = ROOT / "docs" / "IMPLEMENTATION_REPORT.md"

REAL_SOURCE_TEXT = "Every object in the three normative schemas MUST set `additionalProperties: false`."
REAL_IMPL = "schemas/delegation.schema.json"
REAL_TEST = "tests/test_schemas.py::TestClosedSchemas::test_envelope_rejects_unknown_members"


def _run_verifier(tmp_path: Path, inventory_text: str, report_text: str,
                  spec_text: str | None = None, nodes: list[str] | None = None) -> subprocess.CompletedProcess[str]:
    """Run the verifier against temporary fixtures."""
    spec = tmp_path / "spec.md"
    spec.write_text(spec_text or (
        "# Spec\n\n" + REAL_SOURCE_TEXT + "\n\nMore text without MUST here.\n"
    ))
    inv = tmp_path / "inv.json"
    inv.write_text(inventory_text)
    rep = tmp_path / "report.md"
    rep.write_text(report_text)
    nodes_file = tmp_path / "nodes.txt"
    nodes_file.write_text("\n".join(nodes or [REAL_TEST]) + "\n")
    return subprocess.run(
        [sys.executable, str(VERIFIER), "--pytest-nodes", str(nodes_file),
         "--spec", str(spec), "--inventory", str(inv), "--report", str(rep)],
        capture_output=True, text=True, timeout=15,
    )


def _valid_inventory() -> dict:
    return {
        "spec_file": "docs/federated-agent-web-build-spec-v0.2.md",
        "spec_version": "0.2",
        "requirements": [{
            "id": "FAW-V02-6-001",
            "section": "6",
            "source_text": REAL_SOURCE_TEXT,
            "summary": "Closed schemas.",
            "implementation": [REAL_IMPL],
            "tests": [REAL_TEST],
            "evidence_class": "schema enforcement",
            "status": "covered",
        }],
        "excluded_paragraphs": [],
    }


class TestTraceabilityVerifier:
    def test_real_inventory_passes(self, tmp_path):
        """The committed inventory + report + real pytest nodes pass."""
        import sys as _sys
        _sys.path.insert(0, str(ROOT / "scripts"))
        from verify_traceability import main as vmain
        nodes = tmp_path / "nodes.txt"
        subprocess.run(
            [_sys.executable, "-m", "pytest", "--collect-only", "-q", str(ROOT / "tests")],
            capture_output=True, text=True, timeout=60,
        )
        # Reuse the committed node list generated by the CI command
        # by collecting now.
        collected = subprocess.run(
            [_sys.executable, "-m", "pytest", "--collect-only", "-q", str(ROOT / "tests")],
            capture_output=True, text=True, timeout=60,
        )
        nodes.write_text(collected.stdout)
        rc = vmain(["--pytest-nodes", str(nodes), "--inventory", str(INVENTORY),
                    "--report", str(REPORT)])
        assert rc == 0, "committed traceability inventory must pass"

    def test_missing_requirement_rejected(self, tmp_path):
        inv = _valid_inventory()
        inv["requirements"].pop()
        r = _run_verifier(tmp_path, json.dumps(inv), "| FAW-V02-6-001 |")
        assert r.returncode != 0
        assert "missing from inventory" in r.stdout

    def test_duplicate_id_rejected(self, tmp_path):
        inv = _valid_inventory()
        inv["requirements"].append(dict(inv["requirements"][0]))
        r = _run_verifier(tmp_path, json.dumps(inv), "| FAW-V02-6-001 |")
        assert r.returncode != 0
        assert "duplicate requirement ID" in r.stdout

    def test_stale_source_quote_rejected(self, tmp_path):
        inv = _valid_inventory()
        inv["requirements"][0]["source_text"] = "This clause no longer exists in the spec and MUST be detected."
        r = _run_verifier(tmp_path, json.dumps(inv), "| FAW-V02-6-001 |")
        assert r.returncode != 0
        assert "no longer in spec" in r.stdout

    def test_missing_implementation_path_rejected(self, tmp_path):
        inv = _valid_inventory()
        inv["requirements"][0]["implementation"] = ["nonexistent/path.py"]
        r = _run_verifier(tmp_path, json.dumps(inv), "| FAW-V02-6-001 |")
        assert r.returncode != 0
        assert "implementation path missing" in r.stdout

    def test_unknown_pytest_node_rejected(self, tmp_path):
        inv = _valid_inventory()
        inv["requirements"][0]["tests"] = ["tests/nonexistent.py::test_never"]
        r = _run_verifier(tmp_path, json.dumps(inv), "| FAW-V02-6-001 |")
        assert r.returncode != 0
        assert "not collected" in r.stdout

    def test_report_missing_requirement_rejected(self, tmp_path):
        inv = _valid_inventory()
        r = _run_verifier(tmp_path, json.dumps(inv), "| FAW-V02-6-999 |")
        assert r.returncode != 0
        assert "missing from implementation report" in r.stdout

    def test_uncovered_status_rejected(self, tmp_path):
        inv = _valid_inventory()
        inv["requirements"][0]["status"] = "TODO"
        r = _run_verifier(tmp_path, json.dumps(inv), "| FAW-V02-6-001 |")
        assert r.returncode != 0
        assert "status must be 'covered'" in r.stdout

    def test_unjustified_exclusion_rejected(self, tmp_path):
        inv = _valid_inventory()
        inv["excluded_paragraphs"] = [{
            "source_text": "Some paragraph that MUST do something.",
            "reason": "no good reason",
            "classification": "quoted non-normative material",
        }]
        spec_text = "# Spec\n\n" + inv["excluded_paragraphs"][0]["source_text"] + "\n"
        r = _run_verifier(tmp_path, json.dumps(inv), "| FAW-V02-6-001 |", spec_text=spec_text)
        assert r.returncode != 0
        assert "non-normative" in r.stdout
